using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;

namespace Content.Client._Floof.Consent;

[GenerateTypedNameReferences]
public sealed partial class NewConsentText : Control
{
    public Action<string>? OnConsentTextChanged;

    public NewConsentText()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        var loc = IoCManager.Resolve<ILocalizationManager>();
        CConsentTextInput.Placeholder = new Rope.Leaf(loc.GetString("consent-window-freetext-placeholder"));
        CConsentTextInput.OnTextChanged  += _ => ConsentTextChanged();
    }

    public void ConsentTextChanged()
    {
        OnConsentTextChanged?.Invoke(Rope.Collapse(CConsentTextInput.TextRope).Trim());
    }
}
